ID - 39: Order details history page integration
Les-Jailes/Boutique_Clothing pull request #48
Opened 2023-11-23 05:40 UTC by saletG08

### What?

What I did is that the user who is logged in and tries to go to the "Order history" section will search the database if the user made a purchase, but if they did not make a purchase it will show them a screen where it says : "You didn't buy any product!" with a small paragraph that says "Please go see the products in our store to purchase." Later, at the bottom of this paragraph there will be a button that will guide the user to the products they can buy, which the button will say "See Products" and when clicking on the button it will take them to the products screen.
Upon successfully making the purchase, the user will be able to go to the "Order history" screen again and it will show all the products they purchased in a table. Before the table appears it will be loaded with data so that the data can be retrieved until it loads.
The screen is responsive and the table will get smaller.

### How?
I did it with the help of the API that has to send requests to the OrderHistory which was created and it will return the userId with this userId we will look for the user if they buy a product to show in the table.
For the responsive one, only CSS was used to change the letter sizes, colors, among others.

### Why?
I did it with the purpose that the user can see all the products that he made throughout the navigation, in order to see which products he liked or which he is not interested in. In addition, the objective of this week is to complete the purchase and what we have is the visualization of the products that the user has.

Author: @saletG08 
Code Reviewer: @Karvlox 
Tester: @denisgandel

2023-11-23 13:02 UTC, Elvis-Castro-H requested changes
Resolve comments

2023-11-23 13:02 UTC, Elvis-Castro-H commented on next-env.d.ts
delete this file

2023-11-23 13:10 UTC, saletG08 commented on next-env.d.ts
The file has been deleted

2023-11-23 14:26 UTC, Karvlox approved these changes
Good job

2023-11-23 17:50 UTC, victor-villca commented
@saletG08 The UI and functionality of this pull request does not match the one talked on the planning, please fix it.

2023-11-28 01:02 UTC, Elvis-Castro-H approved these changes
Good job

2023-11-28 01:02 UTC, merged